### ISSUE TITLE
USB charging

### ISSUE THREAD

**Issue by mattvilim** [forkeverything/KinesisBLE#1]
This is pretty cool...I'm gonna build one. Just one question...do you remove the keyboard cover every time you charge it? It seems to me it would be better if the feather was rotated 180 degrees and you drilled a hole through the back. Or am I missing something?

**Comment by mattvilim** [comment]
Actually, what about using this? https://www.adafruit.com/product/3258

**Comment by mikewuu** [comment]
Once you take out the original cable there's already a hole there. So you just feed a micro usb cable through 

I actually bought that panel mount but it's width is roughly the same size as the hole. Meaning there isn't enough clearance to fix it to the case securely.

**Comment by mseflek** [comment]
I used the panel mount (at least the USB-C one) by drilling two small holes for the screws by the  hole used for the USB hub: https://imgur.com/l6Ymc5b Seems pretty stable so far.

**Comment by mikewuu** [comment]
Looks good! What did you use as the cap for the original cable opening?

**Comment by mseflek** [comment]
It's probably a bit overkill but I used [this](https://www.amazon.com/gp/product/B07CN14LC8/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1). Any 3/4" diameter plug will do. I also tried drilling into the plug to see if I could get the power button inside but that failed pretty spectacularly, hence why I had to drill another hole.
