### ISSUE TITLE
Split design?

### ISSUE THREAD

**Issue by mseflek** [forkeverything/KinesisBLE#3]
Hi Mike,

Thanks a ton for the help over on the project page. Quick question for you: it seems since you've figured out the wireless aspects of this, any plans/interest to make a version that works on a "split" design? I'm thinking splitting the advantage into two would make it into the ultimate keyboard I've never had, but I don't have the electronics expertise to figure out how that could work alongside your wireless implementation. I guess there are two options here:

1. Use the wireless set up you've got, but have a cable connecting both halves.
2. Set up both sides to be independent with a feather controller for each side, and have them recognized as two separate keyboards/bluetooth devices on the OS side.

Any thoughts on this?

**Comment by mikewuu** [comment]
I've thought of it. I've even wanted to build a Dactyl once but read that the Kinesis had better palm support and so I decided against it. How would you physically split the case though?

For the connection I'd probably use RF to connect the 2 halves, might need an extra controller. Or 2 feathers as you've suggested. Any option will work, the Kinesis keyboard matrixes are functionally 4 separate keyboards. 

If you know how to cleanly build the case I'd be keen to work together on this.

**Comment by mseflek** [comment]
All of the split designs I've seen have been super hacky -- [as in they've probably used a hacksaw to cut it in two.](https://i.imgur.com/S5MzwoX.jpg). I don't think there's really a "clean" way to separate it other than cutting the top and bottom half in two. I suppose one could 3d print an entirely new case similar to what these guys did for an MS trackball explorer (which go for up to $500 bucks on ebay!): https://www.ploopy.co

I would think that one could just split your current PCB design into two and just run a cable between the two halves as a first try. I counted and I think it's at least 11 wires from the RHS that need to connect to the LHS (if you move the port expander to the LHS as well), though it may be more. There may be off-the-shelf cables that can be used. I initially thought maybe a cat 5 cable may cut it but there aren't enough wires.

I'd love to help in any way I can, but to be honest I'm more of a machine learning/data science person, so while I can typically put together other people's projects, I'm not as good coming up with new designs. Happy to help however I can though.

Another "wishlist" idea I had: I'm not sure if you are familiar with the [keymouse](https://www.keymouse.com), but they've integrated a mouse into a split countered keyboard. This might be pushing it but I thought that since the bottom of the contour of the advantage is so close to the desk, one could potentially add a mouse sensor the bottom and change the rubber feet to teflon and have a similar keyboard/mouse hybrid. Again, the implementation of this is totally foreign to me, but I figured if the Feather can help build a bluetooth interface for a keyboard, perhaps it could also do the same with a mouse.

**Comment by mikewuu** [comment]
Unfortunately I'm not a hardware designer either. Cutting the keyboard in half would work electronically, but you'd have to make stands/feet for each half to keep things steady while you type. If you ever figure out a way to make the case, count me in!

**Comment by mseflek** [comment]
Oh good point! I hadn’t realized that the feet were not in a position to keep the keyboard steady when split. I’ll look into it.
