### ISSUE TITLE
Keys aren't registering

### ISSUE THREAD

**Issue by mehmet-diagnoss** [forkeverything/KinesisBLE#4]
Hi Mike,

I built the board without much trouble and checked all connections for continuity all the way to the NRF52, but I'm not able to get any keys working at all. Even the firmware level commands (e.g. reset bluetooth connections) don't seem to elicit a response. The battery indicators work, the board even goes to sleep, and I can see the KinesisBLE in the bluetooth devices on MacOS and can connect to it but key presses seemingly do nothing, on any of the key wells, thumb clusters, or the F rows. They don't even wake up the board. Any ideas? I am using BSP version 0.8.6 as you suggested.

I'm realizing now that maybe I used the wrong port expander for  board version v4? I saw in the components that you had listed MCP23017 or MCP23S17, and I got the former without thinking about it. Maybe I should be using the latter?

**Comment by mikewuu** [comment]
Yes, MCP23017 was for v1/v2 and you'll need MCP23S17 for v4 boards.

**Comment by mehmet-diagnoss** [comment]
Great. Figured as much when reviewing the parts I ordered. Thanks.
