### ISSUE TITLE
Turning off pomodoro timings?

### ISSUE THREAD

**Issue by mseflek** [forkeverything/KinesisBLE#6]
Sorry if I'm getting annoying! Quick question: is there a quick way to turn off the pomodoro timings feature? I looked through the build log but I believe some of the discussions there are outdated wrt to the current firmware.

**Comment by mikewuu** [comment]
No worries, glad you're enjoying the firmware. Just comment out `restCheck()` in `Keyboard::update`

```
void Keyboard::update(void) {
   
  auto update = matrix.scan();
  if (update) {
    idleTime = millis();
    keymap.update(&matrix);
    hid.sendKeys(&keymap);
  }

  led.process();
  //restCheck();
  sleepCheck();
}
```

**Comment by mseflek** [comment]
Thanks! That's helpful. Any problems you foresee with modifying that part of the code and adding an if statement to check for a `REST_TIMER` flag in `config.h`? Was thinking of doing this in my personal fork.

**Comment by mikewuu** [comment]
That might not have any significant impact, but keep in mind that the `update` method is the main loop; your`if` will be constantly checked.

**Comment by mehmet-diagnoss** [comment]
> your `if` will be constantly checked.
Yeah that's what I thought too -- I'll see if I can get around doing that. Thanks!

**Comment by mseflek** [comment]
> your `if` will be constantly checked.

Yeah that's what I thought too -- I'll see if I can get around doing that. Thanks!
